require:
  - rubocop-rails
  - rubocop-rails
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - bin/**/*
    - vendor/**/*
    - db/schema.rb
